### Read Post API Test
get http://localhost:8000/posts/1 HTTP/1.1


### Create Post API Test
post http://localhost:8000/posts HTTP/1.1
Content-Type: application/json

{
    "title": "test post api",
    "content": "test post api content",
    "author_id": 1
}

########################################################################################################################
### Create User API Test
POST http://localhost:8000/users HTTP/1.1
Content-Type: application/json

{
    "email": "gildong19@gmail.com",
    "password": "gildong123",
    "is_active": true
}


### Create JWT API Test
post http://localhost:8000/token HTTP/1.1
Content-Type: application/json

{
    "id": 28,
    "email": "gildong@gmail.com",
    "is_active": true
}

### Read User API Test
GET http://localhost:8000/users/28 HTTP/1.1
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjgsImVtYWlsIjoiZ2lsZG9uZ0BnbWFpbC5jb20iLCJpc19hY3RpdmF0ZSI6dHJ1ZSwiZXhwIjoxNjM1MzMwMzcxfQ.Tl33_HK7tEyK5Tkl9Vt3aNrgyzGfda-S7_IshCxHyY8

### Update User API Test
PUT http://localhost:8000/users/28 HTTP/1.1
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjgsImVtYWlsIjoiZ2lsZG9uZ0BnbWFpbC5jb20iLCJpc19hY3RpdmF0ZSI6dHJ1ZSwiZXhwIjoxNjM1MzMwMzcxfQ.Tl33_HK7tEyK5Tkl9Vt3aNrgyzGfda-S7_IshCxHyY8

{
    "email": "gildong123@naver.com",
    "password": "gildong123",
    "is_active": false
}

GET http://localhost:8000/users/28 HTTP/1.1
Authorization: token 
########################################################################################################################